services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_client_portal_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d ai_client_portal_development",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      MAILER_FROM_ADDRESS: notifications@freelancehub.test
      GCS_PROJECT_ID: freelancehub-502218
      GCS_BUCKET: freelancehub-storage-2026
      GOOGLE_APPLICATION_CREDENTIALS: /rails/config/gcp/freelancehub-gcs-key.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/rails

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails tailwindcss:watch
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
    tty: true

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      MAILER_FROM_ADDRESS: notifications@freelancehub.test
      GCS_PROJECT_ID: freelancehub-502218
      GCS_BUCKET: freelancehub-storage-2026
      GOOGLE_APPLICATION_CREDENTIALS: /rails/config/gcp/freelancehub-gcs-key.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/rails

volumes:
  postgres_data:
  redis_data: